spring:
  application:
    name: spring-integration-lock

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:spring-integration-lock
    username: sa
    password:

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop

  data:
    redis:
      host: localhost
      port: 6379

  h2:
    console:
      enabled: true

logging:
  level:
    org:
      practice: TRACE
      springframework:
        orm:
          jpa:
            JpaTransactionManager: DEBUG
